Added Batch Request
spaceuptech/space-api-java pull request #18
Opened 2019-06-05 12:50 UTC by AliabbasMerchant

@YourTechBud  Done

2019-06-05 18:27 UTC, YourTechBud commented
@AliabbasMerchant you think we should throw an exception for batch.add? Maybe just returb a false if the batch add failed? Im not sure. What do you think?

Also, did you test if it works?

2019-06-06 08:43 UTC, AliabbasMerchant commented
Maybe returning false would be a good idea, but then you would have to exclusively check for the false value every time. An exception would just halt the execution (unless caught), and you can directly write all your multiple statements in a try catch-block.

I haven't tested the batch thing, but assuming that the rest of CRUD works and knowing that the server works, I am hoping that this also works 🤞

2019-06-07 02:00 UTC, YourTechBud requested changes
Minor changes. It was an amazing idea to use function overloading!!

2019-06-07 02:00 UTC, YourTechBud commented on src/main/java/com/spaceuptech/space_api/mongo/Delete.java
> +    private String operation, db, collection;
No need to store db and collection. Its already there in the meta object

2019-06-07 06:15 UTC, AliabbasMerchant commented on src/main/java/com/spaceuptech/space_api/mongo/Delete.java
> +    private String operation, db, collection;
Right. Cool

2019-06-07 06:20 UTC, AliabbasMerchant commented
@YourTechBud Done

2019-06-07 07:37 UTC, merged